/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tugasaplikasi;

/**
 *
 * @author Viann
 */
public class Content_Home extends javax.swing.JPanel {

    /**
     * Creates new form Content_Home
     */
    public Content_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoHome = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Apa = new javax.swing.JLabel();
        Yang = new javax.swing.JLabel();
        Kamu = new javax.swing.JLabel();
        Mau = new javax.swing.JLabel();
        Daftar = new javax.swing.JLabel();
        ln_KKN = new javax.swing.JLabel();
        ln_PKL = new javax.swing.JLabel();
        ln_Wisuda = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        LogoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logo HomePage.png"))); // NOI18N

        Home.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Home.setForeground(new java.awt.Color(0, 153, 153));
        Home.setText("Home");

        Apa.setBackground(new java.awt.Color(0, 102, 102));
        Apa.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        Apa.setForeground(new java.awt.Color(0, 153, 153));
        Apa.setText("Apa");

        Yang.setFont(new java.awt.Font("Segoe UI", 0, 56)); // NOI18N
        Yang.setForeground(new java.awt.Color(0, 153, 153));
        Yang.setText("Yang");

        Kamu.setFont(new java.awt.Font("Segoe UI", 0, 56)); // NOI18N
        Kamu.setForeground(new java.awt.Color(0, 153, 153));
        Kamu.setText("Kamu");

        Mau.setFont(new java.awt.Font("Segoe UI", 0, 56)); // NOI18N
        Mau.setForeground(new java.awt.Color(0, 153, 153));
        Mau.setText("Mau");

        Daftar.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        Daftar.setForeground(new java.awt.Color(0, 153, 153));
        Daftar.setText("Daftar??");

        ln_KKN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ln_KKN.setForeground(new java.awt.Color(0, 153, 153));
        ln_KKN.setText("- Daftar KKN");

        ln_PKL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ln_PKL.setForeground(new java.awt.Color(0, 153, 153));
        ln_PKL.setText("- Daftar PKL/PPL");

        ln_Wisuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ln_Wisuda.setForeground(new java.awt.Color(0, 153, 153));
        ln_Wisuda.setText("- Daftar Wisuda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Home))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Mau)
                                .addGap(18, 18, 18)
                                .addComponent(Daftar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Apa)
                                .addGap(18, 18, 18)
                                .addComponent(Yang)
                                .addGap(18, 18, 18)
                                .addComponent(Kamu))
                            .addComponent(ln_KKN)
                            .addComponent(ln_PKL)
                            .addComponent(ln_Wisuda))))
                .addContainerGap(564, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LogoHome)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Home)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apa)
                    .addComponent(Yang)
                    .addComponent(Kamu))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mau)
                    .addComponent(Daftar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ln_KKN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ln_PKL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ln_Wisuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(LogoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apa;
    private javax.swing.JLabel Daftar;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Kamu;
    private javax.swing.JLabel LogoHome;
    private javax.swing.JLabel Mau;
    private javax.swing.JLabel Yang;
    private javax.swing.JLabel ln_KKN;
    private javax.swing.JLabel ln_PKL;
    private javax.swing.JLabel ln_Wisuda;
    // End of variables declaration//GEN-END:variables
}
